toolwindow.stripe.OCIDevOpsToolKitToolWindow=OCI DevOps ToolKit
toolwindow.title=OCI DevOps ToolKit
toolwindow.description=Plugin Integration for OCI DevOps Portal
dasarathi.notification.group.name=DevOpsToolKit plugin notifications
